#!/usr/bin/env bash
# This Script connects to the server 54.237.2.162 using the users private key
# stored in a file school Found in the users home directory

ssh -i ~/.ssh/school ubuntu@54.237.2.162
